AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-rake

plugins:
  - rubocop-rspec
  - rubocop-performance

Gemspec/DevelopmentDependencies:
  Enabled: false

# Disable alguns cops de RSpec para manter compatibilidade
RSpec/NamedSubject:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
